server:
  port: 8089
spring:
  application:
    name: fzx
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #192.168.1.107
    url: jdbc:mysql://localhost:3306/db_fzx?useUnicode=true&characterEncoding=utf-8
    username: root
    #123456
    password: 123